version: '3.9'
services:
  uniqueDataEntry:
    image: fabiosereno/portfolio.dotnet.dev:0.0.1
    volumes:
      - >-
        ../../app/app_uniqueDataEntry/backend/api:/usr/src/app/app/app_uniqueDataEntry/backend/api
      - ../../backend/Portfolio.Core:/usr/src/app/backend/Portfolio.Core
    container_name: uniqueDataEntry
    command: >-
      sh -c "dotnet build /usr/src/app/app/app_uniqueDataEntry/backend/api &&
      dotnet
      /usr/src/app/app/app_uniqueDataEntry/backend/api/bin/Debug/net7.0/api.dll"
    networks:
      - backend
    ports:
      - '3003:3003'
    mem_limit: 500M
    cpus: 0.2
    depends_on: []
  dataStructures:
    image: fabiosereno/portfolio.dotnet.dev:0.0.1
    volumes:
      - >-
        ../../app/app_dataStructures/backend/api:/usr/src/app/app/app_dataStructures/backend/api
      - ../../backend/Portfolio.Core:/usr/src/app/backend/Portfolio.Core
    container_name: dataStructures
    command: >-
      sh -c "dotnet build /usr/src/app/app/app_dataStructures/backend/api &&
      dotnet
      /usr/src/app/app/app_dataStructures/backend/api/bin/Debug/net7.0/api.dll"
    networks:
      - backend
    ports:
      - '3002:3002'
    mem_limit: 500M
    cpus: 0.2
    depends_on: []
  entitySort:
    image: fabiosereno/portfolio.dotnet.dev:0.0.1
    volumes:
      - >-
        ../../app/app_entitySort/backend/api:/usr/src/app/app/app_entitySort/backend/api
      - ../../backend/Portfolio.Core:/usr/src/app/backend/Portfolio.Core
    container_name: entitySort
    command: >-
      sh -c "dotnet build /usr/src/app/app/app_entitySort/backend/api && dotnet
      /usr/src/app/app/app_entitySort/backend/api/bin/Debug/net7.0/api.dll"
    networks:
      - backend
    ports:
      - '3005:3005'
    mem_limit: 500M
    cpus: 0.2
    depends_on: []
  stringSort:
    image: fabiosereno/portfolio.dotnet.dev:0.0.1
    volumes:
      - >-
        ../../app/app_stringSort/backend/api:/usr/src/app/app/app_stringSort/backend/api
      - ../../backend/Portfolio.Core:/usr/src/app/backend/Portfolio.Core
    container_name: stringSort
    command: >-
      sh -c "dotnet build /usr/src/app/app/app_stringSort/backend/api && dotnet
      /usr/src/app/app/app_stringSort/backend/api/bin/Debug/net7.0/api.dll"
    networks:
      - backend
    ports:
      - '3004:3004'
    mem_limit: 500M
    cpus: 0.2
    depends_on: []
  coffeeMachine:
    image: fabiosereno/portfolio.dotnet.dev:0.0.1
    volumes:
      - >-
        ../../app/app_coffeeMachine/backend/api:/usr/src/app/app/app_coffeeMachine/backend/api
      - ../../backend/Portfolio.Core:/usr/src/app/backend/Portfolio.Core
    container_name: coffeeMachine
    command: >-
      sh -c "dotnet build /usr/src/app/app/app_coffeeMachine/backend/api &&
      dotnet
      /usr/src/app/app/app_coffeeMachine/backend/api/bin/Debug/net7.0/api.dll"
    networks:
      - backend
    ports:
      - '3001:3001'
    mem_limit: 500M
    cpus: 0.2
    depends_on: []
  nginx:
    image: nginx:1.23.1
    ports:
      - '80:80'
    container_name: frontend
    volumes:
      - ../../nginx.dev.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend
      - backend
    mem_limit: 500M
    cpus: 0.2
    depends_on:
      - uniqueDataEntry
      - dataStructures
      - entitySort
      - stringSort
      - coffeeMachine
  node:
    image: fabiosereno/portfolio.dev:0.0.2
    environment:
      - dir=home
    ports:
      - '8080:8080'
    volumes:
      - ../../config.json:/usr/src/app/config.json
      - ../../babel.config.json:/usr/src/app/babel.config.json
      - ../../setupTests.js:/usr/src/app/setupTests.js
      - ../../app:/usr/src/app/app
      - ../../docs:/usr/src/app/docs
      - ../../build:/usr/src/app/build
    container_name: node
    networks:
      - frontend
      - backend
    mem_limit: 500M
    cpus: 0.2
    depends_on:
      - uniqueDataEntry
      - dataStructures
      - entitySort
      - stringSort
      - coffeeMachine
networks:
  frontend: null
  backend: null
