version: '3.9'
services:
  nginx:
    image: nginx:1.23.1
    ports:
      - '80:80'
    container_name: frontend
    networks:
      - frontend
      - backend
    mem_limit: 500M
    cpus: 0.2
networks:
  frontend: null
  backend: null
