version: '3.9'
services:
  nginx:
    image: nginx:1.23.1
    ports:
      - '80:80'
    container_name: frontend
    networks:
      - frontend
      - backend
    mem_limit: 500M
    cpus: 0.2
  node:
    image: fabiosereno/portfolio.dev:0.0.2
    environment:
      - dir=home
    ports:
      - '8080:8080'
    volumes:
      - ../../config.json:/usr/src/app/config.json
      - ../../babel.config.json:/usr/src/app/babel.config.json
      - ../../setupTests.js:/usr/src/app/setupTests.js
      - ../../app:/usr/src/app/app
      - ../../docs:/usr/src/app/docs
      - ../../build:/usr/src/app/build
    container_name: node
    networks:
      - frontend
      - backend
    mem_limit: 500M
    cpus: 0.2
  stringSort:
    image: fabiosereno/portfolio.dotnet.dev:0.0.1
    volumes:
      - >-
        ../../app/app_stringSort/backend/api:/usr/src/app/app/app_stringSort/backend/api
      - ../../backend/Portfolio.Core:/usr/src/app/backend/Portfolio.Core
    container_name: stringSort
    command: >-
      sh -c "dotnet build /usr/src/app/app/app_stringSort/backend/api && dotnet
      /usr/src/app/app/app_stringSort/backend/api/bin/Debug/net7.0/api.dll"
    networks:
      - backend
    ports:
      - '3004:3004'
    mem_limit: 500M
    cpus: 0.2
  coffeeMachine:
    image: fabiosereno/portfolio.dotnet.dev:0.0.1
    volumes:
      - >-
        ../../app/app_coffeeMachine/backend/api:/usr/src/app/app/app_coffeeMachine/backend/api
      - ../../backend/Portfolio.Core:/usr/src/app/backend/Portfolio.Core
    container_name: coffeeMachine
    command: >-
      sh -c "dotnet build /usr/src/app/app/app_coffeeMachine/backend/api &&
      dotnet
      /usr/src/app/app/app_coffeeMachine/backend/api/bin/Debug/net7.0/api.dll"
    networks:
      - backend
    ports:
      - '3001:3001'
    mem_limit: 500M
    cpus: 0.2
networks:
  frontend: null
  backend: null
