version: '3.9'

services:
    node:
        image: 'fabiosereno/portfolio.dev:0.0.2'
        environment:
            - dir=${DIR:-home}
        ports:
            - '8080:8080'
        volumes:
            - '../../config.json:/usr/src/app/config.json'
            - '../../babel.config.json:/usr/src/app/babel.config.json'
            - '../../setupTests.js:/usr/src/app/setupTests.js'
            - '../../app:/usr/src/app/app'
            - '../../docs:/usr/src/app/docs'
            - '../../build:/usr/src/app/build'
        container_name: node
        networks:
            - frontend
            - backend
        depends_on:
            - api
        mem_limit: 500M
        cpus: 0.2
    nginx:
        image: 'nginx:1.23.1'
        ports:
            - '80:80'
        environment:
            - NAME=${DIR}
        container_name: frontend
        networks:
            - frontend
            - backend
        depends_on:
            - api
            - node
        mem_limit: 500M
        cpus: 0.2
    api:
        image: 'fabiosereno/portfolio.dotnet.dev:0.0.1'
        volumes:
            - '../../app/app_${DIR}/backend/api:/usr/src/app/app/app_${DIR}/backend/api'
            - '../../backend/Portfolio.Core:/usr/src/app/backend/Portfolio.Core'
        container_name: ${DIR}
        command: sh -c "dotnet build /usr/src/app/app/app_${DIR}/backend/api && dotnet /usr/src/app/app/app_${DIR}/backend/api/bin/Debug/net7.0/api.dll"
        networks:
            - backend
        mem_limit: 500M
        cpus: 0.2