version: '3.9'

services:
    backend:
        image: 'fabiosereno/portfolio.dotnet.api.0.0.3'
        ports:
            - '3000:3000'
        container_name: backend
        networks:
            - frontend
            - backend
networks:
    frontend:
    backend: