# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    gulp tests --gulpfile gulpfile.js
    gulp publish
    dotnet test app/app_dotnetCore --configuration $(buildConfiguration)
    dotnet test app/app_awsDotNetCoreShoppingCart/aws/test/aws.Tests --configuration $(buildConfiguration)
  displayName: 'npm install, gulp tasks, dotnet project build and tests.'