version: '3.9'

services:
    server:
        image: 'fabiosereno/portfolio:1.10.0'
        ports:
            - '8080:8080'
        volumes:
            - './app:/usr/src/app/app'
           # issue with pattern matching, need to be specifc ?

# docker container run -d --name port -p 8080:8080 -v $(pwd)/app:/usr/src/app/app
# -v $(pwd)/gulpfile.js:/usr/src/app/gulpfile.js fabiosereno/portfolio:1.10.0
# may want to mount docs ? 
