version: '3.9'
services:
  nodeToDo:
    image: fabiosereno/portfolio.node.dev:1.0.0
    container_name: nodeToDo
    networks:
      - backend
    ports:
      - '3006:3006'
    mem_limit: 500M
    cpus: 0.2
    depends_on: []
    volumes:
      - ./app/app_nodeToDo/backend/api:/usr/src/app/app/app_nodeToDo/backend/api
    command: sh -c "node /usr/src/app/app/app_nodeToDo/backend/api/index.js"
  nginx:
    image: nginx:1.23.1
    ports:
      - '80:80'
    container_name: nginx
    networks:
      - frontend
      - backend
    mem_limit: 500M
    cpus: 0.2
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nodeToDo
  server:
    image: fabiosereno/portfolio.dev:1.0.0
    environment:
      - dir=${DIR:-home}
    ports:
      - '8080:8080'
    volumes:
      - ./config.json:/usr/src/app/config.json
      - ./babel.config.json:/usr/src/app/babel.config.json
      - ./setupTests.js:/usr/src/app/setupTests.js
      - ./app:/usr/src/app/app
      - ./docs:/usr/src/app/docs
      - ./build:/usr/src/app/build
    container_name: server
    networks:
      - frontend
      - backend
    mem_limit: 500M
    cpus: 0.2
    depends_on:
      - nodeToDo
networks:
  frontend: null
  backend: null
