version: '3.9'

services:
    server:
        tty: true
        image: 'fabiosereno/portfolio:1.31.0'
        ports:
            - '8080:8080'
        volumes:
            - './config.json:/usr/src/app/config.json'
            - './babel.config.json:/usr/src/app/babel.config.json'
            - './app:/usr/src/app/app'
            - './docs:/usr/src/app/docs'
            - './build:/usr/src/app/build'
