version: '3.9'

services:
    nginx:
        image: 'fabiosereno/portfolio.nginx:0.4.0'
        x-aws-pull_credentials: 'arn:aws:secretsmanager:eu-west-2:523190279095:secret:dockerhubAccessToken-1JuRZX'
        ports:
            - '80:80'
        container_name: frontend
        networks:
            - frontend
            - backend
        depends_on:
            - "coffeeMachine"
            - "dataStructures"
            - "uniqueDataEntry"
            - "stringSort"
            - "entitySort"
            - "nodeToDo"
        mem_limit: 500M
        cpus: 0.2
    coffeeMachine:
        image: 'fabiosereno/portfolio.coffee-machine:0.0.15'
        x-aws-pull_credentials: 'arn:aws:secretsmanager:eu-west-2:523190279095:secret:dockerhubAccessToken-1JuRZX'
        ports:
            - '3001:3001'
        container_name: coffeeMachine
        networks:
            - backend
        mem_limit: 500M
        cpus: 0.2
    dataStructures:
        image: 'fabiosereno/portfolio.data-structures:0.0.5'
        x-aws-pull_credentials: 'arn:aws:secretsmanager:eu-west-2:523190279095:secret:dockerhubAccessToken-1JuRZX'
        ports:
            - '3002:3002'
        container_name: dataStructures
        networks:
            - backend
        mem_limit: 500M
        cpus: 0.2
    uniqueDataEntry:
        image: 'fabiosereno/portfolio.unique-data-entry:0.0.2'
        x-aws-pull_credentials: 'arn:aws:secretsmanager:eu-west-2:523190279095:secret:dockerhubAccessToken-1JuRZX'
        ports:
            - '3003:3003'
        container_name: uniqueDataEntry
        networks:
            - backend
        mem_limit: 500M
        cpus: 0.2
    stringSort:
        image: 'fabiosereno/portfolio.string-sort:0.0.1'
        x-aws-pull_credentials: 'arn:aws:secretsmanager:eu-west-2:523190279095:secret:dockerhubAccessToken-1JuRZX'
        ports:
            - '3004:3004'
        container_name: stringSort
        networks:
            - backend
        mem_limit: 500M
        cpus: 0.2
    entitySort:
        image: 'fabiosereno/portfolio.entity-sort:0.0.4'
        x-aws-pull_credentials: 'arn:aws:secretsmanager:eu-west-2:523190279095:secret:dockerhubAccessToken-1JuRZX'
        ports:
            - '3005:3005'
        container_name: entitySort
        networks:
            - backend
        mem_limit: 500M
        cpus: 0.2
    nodeToDo:
        image: 'fabiosereno/portfolio.node-to-do:0.0.1'
        x-aws-pull_credentials: 'arn:aws:secretsmanager:eu-west-2:523190279095:secret:dockerhubAccessToken-1JuRZX'
        ports:
            - '3006:3006'
        container_name: nodeToDo
        networks:
            - backend
        mem_limit: 500M
        cpus: 0.2
networks:
    frontend:
    backend: