version: '3.9'

services:
    server:
        tty: true
        image: 'fabiosereno/portfolio:1.26.0'
        ports:
            - '8080:8080'
        volumes:
            - './app:/usr/src/app/app'
            - './config.json:/usr/src/app/config.json'
            - './babel.config.json:/usr/src/app/babel.config.json'
            - './webpack.config.master.js:/usr/src/app/webpack.config.master.js'
            - './webpack.config.vendor.js:/usr/src/app/webpack.config.vendor.js'
            - './webpack.config.js:/usr/src/app/webpack.config.js'
            - './webpackBuilder.js:/usr/src/app/webpackBuilder.js'
            - './webpackHelper.js:/usr/src/app/webpackHelper.js'
            - './gulpfile.js:/usr/src/app/gulpfile.js'
            - './gulpUtil.js:/usr/src/app/gulpUtil.js'
            - './docs:/usr/src/app/docs'
            - './dist:/usr/src/app/dist'
