version: '3.9'
services:
  nginx:
    image: nginx:1.23.1
    ports:
      - '80:80'
    container_name: nginx
    networks:
      - frontend
      - backend
    mem_limit: 500M
    cpus: 0.2
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on: []
  node:
    image: fabiosereno/portfolio.analysis:0.0.3
    environment:
      - dir=coffeeMachine
    ports:
      - '8080:8080'
    volumes:
      - ./config.json:/usr/src/app/config.json
      - ./babel.config.json:/usr/src/app/babel.config.json
      - ./setupTests.js:/usr/src/app/setupTests.js
      - ./app:/usr/src/app/app
      - ./docs:/usr/src/app/docs
      - ./build:/usr/src/app/build
    container_name: node
    networks:
      - frontend
      - backend
    mem_limit: 500M
    cpus: 0.2
    depends_on: []
networks:
  frontend: null
  backend: null
