version: '3.9'
services:
  entitySort:
    image: fabiosereno/portfolio.dotnet.dev:1.0.0
    container_name: entitySort
    networks:
      - backend
    ports:
      - '3005:3005'
    mem_limit: 500M
    cpus: 0.2
    depends_on: []
    volumes:
      - >-
        ./app/app_entitySort/backend/api:/usr/src/app/app/app_entitySort/backend/api
      - ./backend/Portfolio.Core:/usr/src/app/backend/Portfolio.Core
    command: >-
      sh -c "dotnet build /usr/src/app/app/app_entitySort/backend/api && dotnet
      /usr/src/app/app/app_entitySort/backend/api/bin/Debug/net8.0/api.dll"
  nginx:
    image: nginx:1.23.1
    ports:
      - '80:80'
    container_name: nginx
    networks:
      - frontend
      - backend
    mem_limit: 500M
    cpus: 0.2
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - entitySort
  server:
    image: fabiosereno/portfolio.dev:1.0.0
    environment:
      - dir=${DIR:-home}
    ports:
      - '8080:8080'
    volumes:
      - ./config.json:/usr/src/app/config.json
      - ./babel.config.json:/usr/src/app/babel.config.json
      - ./setupTests.js:/usr/src/app/setupTests.js
      - ./app:/usr/src/app/app
      - ./docs:/usr/src/app/docs
      - ./build:/usr/src/app/build
    container_name: server
    networks:
      - frontend
      - backend
    mem_limit: 500M
    cpus: 0.2
    depends_on:
      - entitySort
networks:
  frontend: null
  backend: null
