version: '3.9'

services:
    nginx:
        image: 'fabiosereno/portfolio.nginx:0.0.26'
        x-aws-pull_credentials: 'arn:aws:secretsmanager:eu-west-2:523190279095:secret:dockerhubAccessToken-1JuRZX'
        ports:
            - '80:80'
        container_name: frontend
        networks:
            - frontend
            - backend
        depends_on:
            - "coffeeMachine"
            - "dataStructures"
            - "uniqueDataEntry"
    coffeeMachine:
        image: 'fabiosereno/portfolio.coffee-machine:0.0.15'
        x-aws-pull_credentials: 'arn:aws:secretsmanager:eu-west-2:523190279095:secret:dockerhubAccessToken-1JuRZX'
        ports:
            - '3001:3001'
        container_name: coffeeMachine
        networks:
            - backend
    dataStructures:
        image: 'fabiosereno/portfolio.data-structures:0.0.5'
        x-aws-pull_credentials: 'arn:aws:secretsmanager:eu-west-2:523190279095:secret:dockerhubAccessToken-1JuRZX'
        ports:
            - '3002:3002'
        container_name: dataStructures
        networks:
            - backend
    uniqueDataEntry:
        image: 'fabiosereno/portfolio.unique-data-entry:0.0.2'
        x-aws-pull_credentials: 'arn:aws:secretsmanager:eu-west-2:523190279095:secret:dockerhubAccessToken-1JuRZX'
        ports:
            - '3003:3003'
        container_name: uniqueDataEntry
        networks:
            - backend
networks:
    frontend:
    backend:
