version: '3.9'
services:
  entitySort:
    image: fabiosereno/portfolio.entity-sort:1.0.0
    container_name: entitySort
    networks:
      - backend
    ports:
      - '3005:3005'
    mem_limit: 500M
    cpus: 0.2
    depends_on: []
    x-aws-pull_credentials: >-
      arn:aws:secretsmanager:eu-west-2:523190279095:secret:dockerhubAccessToken-1JuRZX
  nginx:
    image: fabiosereno/portfolio.nginx:1.1.4
    ports:
      - '80:80'
    container_name: nginx
    networks:
      - frontend
      - backend
    mem_limit: 500M
    cpus: 0.2
    x-aws-pull_credentials: >-
      arn:aws:secretsmanager:eu-west-2:523190279095:secret:dockerhubAccessToken-1JuRZX
    depends_on:
      - entitySort
networks:
  frontend: null
  backend: null
