version: '3.9'
services:
  dataStructures:
    image: fabiosereno/portfolio.data-structures:1.0.0
    container_name: dataStructures
    networks:
      - backend
    ports:
      - '3002:3002'
    mem_limit: 500M
    cpus: 0.2
    depends_on: []
    x-aws-pull_credentials: >-
      arn:aws:secretsmanager:eu-west-2:523190279095:secret:dockerhubAccessToken-1JuRZX
  nginx:
    image: fabiosereno/portfolio.nginx:1.1.3
    ports:
      - '80:80'
    container_name: nginx
    networks:
      - frontend
      - backend
    mem_limit: 500M
    cpus: 0.2
    x-aws-pull_credentials: >-
      arn:aws:secretsmanager:eu-west-2:523190279095:secret:dockerhubAccessToken-1JuRZX
    depends_on:
      - dataStructures
networks:
  frontend: null
  backend: null
