version: '3.9'

services:
    node:
        tty: true
        image: 'fabiosereno/portfolio.dev:0.0.2'
        environment:
            - dir=${DIR:-home}
        ports:
            - '8080:8080'
        volumes:
            - './config.json:/usr/src/app/config.json'
            - './babel.config.json:/usr/src/app/babel.config.json'
            - './setupTests.js:/usr/src/app/setupTests.js'
            - './app:/usr/src/app/app'
            - './docs:/usr/src/app/docs'
            - './build:/usr/src/app/build'
        container_name: node
        networks:
            - frontend
            - backend
        depends_on:
            - "backend"
    nginx:
        image: 'fabiosereno/portfolio.nginx.dev:0.0.2'
        ports:
            - '80:80'
        container_name: frontend
        networks:
            - frontend
            - backend
        depends_on:
            - "backend"
    backend:
        image: 'fabiosereno/portfolio.api:0.0.6'
        ports:
            - '3000:3000'
        container_name: backend
        networks:
            - backend
networks:
    frontend:
    backend: