version: '3.9'
services:
  uniqueDataEntry:
    image: fabiosereno/portfolio.unique-data-entry:0.0.2
    container_name: uniqueDataEntry
    networks:
      - backend
    ports:
      - '3003:3003'
    mem_limit: 500M
    cpus: 0.2
    depends_on: []
    x-aws-pull_credentials: >-
      arn:aws:secretsmanager:eu-west-2:523190279095:secret:dockerhubAccessToken-1JuRZX
  dataStructures:
    image: fabiosereno/portfolio.data-structures:0.0.5
    container_name: dataStructures
    networks:
      - backend
    ports:
      - '3002:3002'
    mem_limit: 500M
    cpus: 0.2
    depends_on: []
    x-aws-pull_credentials: >-
      arn:aws:secretsmanager:eu-west-2:523190279095:secret:dockerhubAccessToken-1JuRZX
  entitySort:
    image: fabiosereno/portfolio.entity-sort:0.0.4
    container_name: entitySort
    networks:
      - backend
    ports:
      - '3005:3005'
    mem_limit: 500M
    cpus: 0.2
    depends_on: []
    x-aws-pull_credentials: >-
      arn:aws:secretsmanager:eu-west-2:523190279095:secret:dockerhubAccessToken-1JuRZX
  stringSort:
    image: fabiosereno/portfolio.string-sort:0.0.1
    container_name: stringSort
    networks:
      - backend
    ports:
      - '3004:3004'
    mem_limit: 500M
    cpus: 0.2
    depends_on: []
    x-aws-pull_credentials: >-
      arn:aws:secretsmanager:eu-west-2:523190279095:secret:dockerhubAccessToken-1JuRZX
  coffeeMachine:
    image: fabiosereno/portfolio.coffee-machine:0.0.15
    container_name: coffeeMachine
    networks:
      - backend
    ports:
      - '3001:3001'
    mem_limit: 500M
    cpus: 0.2
    depends_on: []
    x-aws-pull_credentials: >-
      arn:aws:secretsmanager:eu-west-2:523190279095:secret:dockerhubAccessToken-1JuRZX
  nginx:
    image: fabiosereno/portfolio.nginx:0.6.0
    ports:
      - '80:80'
    container_name: nginx
    networks:
      - frontend
      - backend
    mem_limit: 500M
    cpus: 0.2
    x-aws-pull_credentials: >-
      arn:aws:secretsmanager:eu-west-2:523190279095:secret:dockerhubAccessToken-1JuRZX
    depends_on:
      - uniqueDataEntry
      - dataStructures
      - entitySort
      - stringSort
      - coffeeMachine
networks:
  frontend: null
  backend: null
