FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base

WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src

RUN apt-get update \
    && apt-get install -y curl

# Entry point to keep the container running
CMD ["tail", "-f", "/dev/null"]