version: '3.9'

services:
    test-dotnet:
        image: 'fabiosereno/portfolio.dotnet.dev:0.0.1'
        volumes:
            - '../../app/app_${DIR}/backend/api:/usr/src/app/app/app_${DIR}/backend/api'
            - '../../app/app_${DIR}/backend/test:/usr/src/app/app/app_${DIR}/backend/test'
            - '../../backend/Portfolio.Core:/usr/src/app/backend/Portfolio.Core'
        container_name: test-dotnet
        command: sh -c "dotnet build /usr/src/app/app/app_${DIR}/backend/test && dotnet test /usr/src/app/app/app_${DIR}/backend/test/test.csproj"
        mem_limit: 500M
        cpus: 0.2