version: '3.9'

services:
    entitySort:
        image: 'fabiosereno/portfolio.entity-sort:0.0.1'
        ports:
            - '3005:3005'
        container_name: entitySort
        networks:
            - backend
networks:
    frontend:
    backend: