version: '3.9'

services:
    node:
        extends:
            file: ../dev/docker-compose.dev.yml
            service: node
        networks:
            - frontend
            - backend
        depends_on:
            - api
        mem_limit: 500M
        cpus: 0.2
    nginx:
        image: 'nginx:1.23.1'
        ports:
            - '80:80'
        environment:
            - NAME=${DIR}
        container_name: frontend
        networks:
            - frontend
            - backend
        depends_on:
            - api
            - node
        volumes:
          - './nginx.dev.conf:/etc/nginx/conf.d/default.conf'
        mem_limit: 500M
        cpus: 0.2
    api:
        image: 'fabiosereno/portfolio.dotnet.dev:0.0.1'
        volumes:
            - '../../app/app_${DIR}/backend/api:/usr/src/app/app/app_${DIR}/backend/api'
            - '../../backend/Portfolio.Core:/usr/src/app/backend/Portfolio.Core'
        ports:
            - '3002:3002'
        container_name: ${DIR}
        command: sh -c "dotnet build /usr/src/app/app/app_${DIR}/backend/api && dotnet /usr/src/app/app/app_${DIR}/backend/api/bin/Debug/net7.0/api.dll"
        networks:
            - backend
        mem_limit: 500M
        cpus: 0.2
networks:
    frontend:
    backend: