version: '3.9'

services:
    dataStructures:
        image: 'fabiosereno/portfolio.data-structures:0.0.5'
        ports:
            - '3002:3002'
        container_name: dataStructures
        networks:
            - backend
networks:
    frontend:
    backend: