POST https://t8txttdaee.execute-api.eu-west-2.amazonaws.com/Prod/api/values/sort HTTP/1.1
content-type: application/json

{"CommaSeperatedString":"document_A2A.txt,document_A1.txt,document_A1B.txt,document_A10A.txt,document_A1A.txt"}


