version: '3.9'

services:
    coffeeMachine:
        image: 'fabiosereno/portfolio.coffee-machine:1.0.0'
        ports:
            - '3001:3001'
        container_name: coffeeMachine
        networks:
            - backend
networks:
    frontend:
    backend: