version: '3.9'

services:
    node:
        extends:
            file: ../dev/docker-compose.dev.yml
            service: node
    nginx:
        extends:
            file: ../dev/docker-compose.dev.yml
            service: nginx
        volumes:
          - './nginx.dev.conf:/etc/nginx/conf.d/default.conf'
          - '../dev/nginx.node.conf:/etc/nginx/conf.d/nginx.node.conf'
    api:
        extends:
            file: ../dev/docker-compose.dev.yml
            service: api
        ports:
            - '3001:3001'
networks:
    frontend:
    backend: