version: '3.9'

services:
    nodeToDo:
        image: 'fabiosereno/portfolio.node-to-do:1.0.0'
        ports:
            - '3006:3006'
        container_name: nodeToDo
        networks:
            - backend
networks:
    frontend:
    backend: